# Coplete NUMPY Documentation

# 1. Array Creation Function

In [17]:
import numpy as np

In [18]:
# Create an array from a list 
a =np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [19]:
#Creat an array with evenly spaced values
b=np.arange(0,10,2) #Value from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 2 4 6 8]


In [20]:
#Creat an array with linealy spaced values 
c = np.linspace(0,1,5) #5values evenly spaced between 0 to 1
print("Array d:\n", c)

Array d:
 [0.   0.25 0.5  0.75 1.  ]


In [21]:
#Creatan array filled with Zeros
d = np.zeros((2,3)) #2*3 array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Creat an array filled with ones
e = np.ones((3,4)) #3*4 arrao of ones
print("Array e:\n",e)

Array e:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
#Creat an identity matrix 
f =np.eye(5) #4*4 identity matrix
print("Indentity Matrix f:\n",f)

Indentity Matrix f:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 2. Array Manipulation Fuction

In [24]:
# Reshsape an array
a1 =np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) #reshape array 3*1
print("Reshaped array :\n",reshaped)

Reshaped array :
 [[1]
 [2]
 [3]]


In [25]:
#Flatted an aaray
f1 = np.array([[1,2],[3,4]])
flatted=np.ravel(f1) #Flatted to 1D array
print("Flatted array:",flatted)

Flatted array: [1 2 3 4]


In [26]:
#Transpose an array
e1=np.array([[1,2],[3,4]])
transpose=np.transpose(e1) #Transpose to array
print("Transpose array:\n",transpose)

Transpose array:
 [[1 3]
 [2 4]]


In [27]:
#Stack arrays vertically
a2 =np.array([1,2])
b2 =np.array([3,4,])
stacked =np.vstack([a2,b2]) #stack a and b vertically
print("Stacked array:\n",stacked)

Stacked array:
 [[1 2]
 [3 4]]


# 3. Mathematical Functions

In [28]:
# Add two arrays
g =np.array([1,2,3,4])
added =np.add(g,2) #add 2 to each element
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [29]:
#Square each element
squared = np.power(g,2) #Square each element
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [30]:
#Square root of each element
sqrt_va1 =np.sqrt(g) #Square root of each element
print("Square root of g;",sqrt_va1)

Square root of g; [1.         1.41421356 1.73205081 2.        ]


In [31]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [32]:
# Dot product of two arrays
a2 = np.array([5,6,7])
dot_product=np.dot(a2,g) #Dot product of a and g
print("Dot product of a and g:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [33]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [34]:
a3 =np.array([4,5,6])
dot_product =np.dot(a3,a) #Dot product of a1 and g
print("Dot product of a3 and a:",dot_product)

Dot product of a3 and a: 32


# 4.Statical Function

In [35]:
s =np.array([1,2,3,4])
mean =np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [36]:
#Satndard derivation of an array
std_dev=np.std(s)
print("Stamdard derivation of s:",std_dev)

Stamdard derivation of s: 1.118033988749895


In [37]:
# Minimum of an array
minimum =np.min(s)
print("minimum of s:",minimum)

minimum of s: 1


In [38]:
# Max of an array
maximum = np.max(s)
print("Maximum of s:",maximum)

Maximum of s: 4


# 5.Linear Algebra Function

In [39]:
#Creat a matrix
matrix =np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [40]:
#Determinant of a matrix
determinant=np.linalg.det(matrix)
print("Dterminant of matrix:",determinant)

Dterminant of matrix: -2.0000000000000004


In [41]:
# Invers of a matrix
inverse =np.linalg.inv(matrix)
print("Inverse of a matrix:\n",inverse)

Inverse of a matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random sampling Function

In [42]:
#Generat random value between 0 and 1 
random_vals=np.random.randn(3) #Array of 3 random value between 0 and 1
print("Random values :",random_vals)

Random values : [ 0.29315941 -0.34608224  1.33246346]


In [43]:
#set seed for reproducibility
np.random.seed(0)

#Generate random values between 0 and 1
random_vals=np.random.rand(3)
print("Random values :",random_vals)

Random values : [0.5488135  0.71518937 0.60276338]


In [44]:
#Generate random integer
rand_ints = np.random.randint(0,20,size=5) #Random integer between o and 20
print("Random intergers:", rand_ints)

Random intergers: [ 3  7  9 19 18]


In [45]:
# set seed for reproductibility 
np.random.seed(0)

#Generate random interger
rand_int=np.random.randint(0,20,size=5) #Random integer between 0 to 20 
print("Random integer :",rand_int)

Random integer : [12 15  0  3  3]


# 7. Boolean & Logical Functions

In [46]:
# Check if all elements both are  True and False
# all 
logical_test=np.array([True,False,True])
all_true =np.all(logical_test)
print("All elements True :",all_true)

All elements True : False


In [47]:
# Check if all element are False 
logical_test1=np.array([False,False,False])
all_false=np.all(logical_test1)
print("All element False:",all_false)

All element False: False


In [48]:
#Checkn if all elements are True 
logical_test2 = np.array([True,True,True,True])
all_true1=np.all(logical_test2)
print("All elements True:",all_true1)

All elements True: True


In [49]:
#Check if any element are true
#Any
any_true=np.any(logical_test)
print("Any elemt True:",any_true)

Any elemt True: True


In [50]:
any_true1=np.any(logical_test1)
print("any element True :",any_true1)

any element True : False


In [51]:
any_true2=np.any(logical_test2)
print("Any elements True:",any_true2)

Any elements True: True


# 8.Set Operation

In [52]:
#Intersection of two arrays 
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [53]:
# Union of two arrays 
union=np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# 9.Array Attributes function

In [54]:
# Array Atributes
a=np.array([1,2,3])
shape=a.shape #shape of the array
size =a.size #Number of elements
dimentions =a.ndim #Numbers of dimentions
dtype =a.dtype #Data type of array

print("shape of a:",shape)
print("size of a :",size)
print("dimentions of a:",dimentions)
print("Data type of a:",dtype)

shape of a: (3,)
size of a : 3
dimentions of a: 1
Data type of a: int32


# 10. Other Functions

In [55]:
# Creat a copy of an array
a = np.array([1,2,3,4])
copied =np.copy(a)  # Creat a copy of array a
print("Copied array:",copied)

Copied array: [1 2 3 4]


In [56]:
# Size in bytes of an array
array_size_in_byte =a.nbytes #size in  bytes
print("Size of a in bytes:",array_size_in_byte)

Size of a in bytes: 16


In [57]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied) #Check if array share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False


# Numpy Crash Course

In [58]:
np.__version__

'1.26.4'

In [59]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating Array

In [60]:
my_list= [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [61]:
type(my_list)

list

In [62]:
arr =np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [63]:
type(arr)

numpy.ndarray

- We learn impoartant function

- Arange function

In [64]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
np.arange(3.0)

array([0., 1., 2.])

In [66]:
np.arange(10) # Creat an array 0 to n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
np.arange(10,25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
np.arange(25,10) #1st argument<2nd argument

array([], dtype=int32)

In [70]:
np.arange(-20,0)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [71]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [72]:
np.arange(-12,8)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,
         1,   2,   3,   4,   5,   6,   7])

In [73]:
np.arange(-20,-5)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6])

In [74]:
ar =np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [75]:
np.arange(10,10)

array([], dtype=int32)

In [76]:
np.arange() #requres one argument

TypeError: arange() requires stop to be specified.

In [77]:
np.arange(10,40,5) # 10-strating from 40-1 end poit 5- step count

array([10, 15, 20, 25, 30, 35])

In [78]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [79]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

- Zeros function

In [80]:
np.zeros(3) #Parameter tunning

array([0., 0., 0.])

In [81]:
np.zeros(5,dtype = int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [82]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [83]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [84]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [85]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
np.zeros((10,20),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [88]:
np.zeros((5,10),dtype=int) # bydefault 1st arg -- will give row & 2nd arg -- column

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [89]:
n= (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [90]:
print(np.zeros(n, dtype=int)) #hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


- Ones Function

In [91]:
n

(6, 7)

In [92]:
n1

(6, 8)

In [93]:
np.ones(3)

array([1., 1., 1.])

In [94]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [96]:
n

(6, 7)

In [97]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [98]:
print(np.ones(n,dtype=int))

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [99]:
np.twoes((2,3))

AttributeError: module 'numpy' has no attribute 'twoes'

- Range Function

In [100]:
range(5)


range(0, 5)

In [101]:
r =range(5)
r

range(0, 5)

In [102]:
for i in r:
    print(i)

0
1
2
3
4


In [103]:
list(range(5))

[0, 1, 2, 3, 4]

In [104]:
range(0,19)

range(0, 19)

In [105]:
list(range(0,19))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [106]:
y = list(range(0,10))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [107]:
for i in y:
    print(i)

0
1
2
3
4
5
6
7
8
9


- Random Function

In [108]:
rand(3,2)
random.rand(3,2)


NameError: name 'rand' is not defined

In [109]:
np.random.rand(5)

array([0.84725174, 0.6235637 , 0.38438171, 0.29753461, 0.05671298])

In [110]:
np.rand(5)


AttributeError: module 'numpy' has no attribute 'rand'

In [111]:
np.random.rand(2,5)

array([[0.27265629, 0.47766512, 0.81216873, 0.47997717, 0.3927848 ],
       [0.83607876, 0.33739616, 0.64817187, 0.36824154, 0.95715516]])

In [112]:
np.random.randint(1,10)

1

In [113]:
np.random.randint(2,20)

5

In [114]:
np.random.randint(1,20,4)

array([18, 15,  8,  1])

In [115]:
np.random.rand(3)

array([0.58201979, 0.53737323, 0.75861562])

In [116]:
np.random.randint(1)



0

In [117]:
np.random.randint(10,20,3)


array([14, 17, 13])

In [118]:
np.random.randint(30,20,10)

ValueError: low >= high

In [119]:
np.random.randint(-30,10,5)

array([-19,  -2,   4, -30, -30])

In [120]:
np.random.randint(20,30,10)

array([24, 25, 25, 26, 28, 24, 21, 24, 29, 28])

In [121]:
np.random.randint(5,9)

6

In [122]:
np.random.randint(10,21,3)

array([11, 17, 19])

In [123]:
np.random.randint(10,30,(10,10)) #generate the element 10 to 30 with 4*4 matrix

array([[13, 16, 21, 24, 28, 10, 24, 13, 22, 20],
       [21, 14, 16, 14, 25, 13, 22, 14, 18, 24],
       [25, 13, 25, 23, 26, 27, 15, 19, 13, 10],
       [15, 10, 27, 28, 14, 12, 26, 13, 12, 20],
       [23, 26, 17, 19, 10, 20, 28, 21, 12, 12],
       [13, 13, 28, 24, 13, 27, 28, 24, 19, 11],
       [14, 20, 21, 18, 21, 12, 29, 26, 10, 10],
       [16, 29, 24, 20, 29, 18, 23, 12, 13, 12],
       [21, 23, 26, 18, 18, 29, 18, 12, 13, 22],
       [24, 10, 14, 13, 23, 21, 23, 23, 21, 26]])

In [124]:
np.random.randint(1,100,(12,12))

array([[25, 30, 22, 26, 81, 61, 62, 84, 34, 33, 71, 86],
       [32, 14, 72, 57, 25, 80, 42, 19, 41, 55, 80, 12],
       [39, 94,  2, 96, 45, 89, 25, 68, 83,  4, 77, 36],
       [87, 62, 70, 88, 44, 33, 12, 85, 11, 55, 38, 29],
       [ 3, 28, 84, 90, 24, 54, 52, 47, 21, 54, 30, 68],
       [36, 40, 10, 74, 42, 24,  4, 47, 91, 51,  4, 32],
       [10, 11, 28, 46, 72, 40, 62, 86, 98, 45, 35, 35],
       [89, 34,  6, 37,  1, 76, 35, 70, 54, 81, 63,  9],
       [62,  2, 82, 36, 92, 41, 37, 49, 26, 68, 36, 31],
       [30, 34, 19, 18, 94, 85,  3, 70, 13, 45, 67, 92],
       [86, 40, 40, 76, 23, 31, 18, 71, 72, 19, 93, 44],
       [84, 50, 42, 94, 47, 22, 74, 90, 97, 92, 74, 29]])

- Resha[pe Function

In [125]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [127]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

- Slicing Function

In [128]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [129]:
type(b)

numpy.ndarray

In [130]:
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [131]:
b[:]

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [132]:
b[:3]

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18]])

In [133]:
b[1:3]

array([[10, 14, 18, 14],
       [13, 13, 18, 18]])

In [134]:
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [135]:
b[1,2] # Select specific element 1st arg - row and 2nd arg - column

18

In [136]:
# select element 18 of 2nd row
b[2,3]

18

In [137]:
b[1,2]

18

In [138]:
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [139]:
b[1,3]

14

In [140]:
b[1,-1]

14

In [141]:
b[2:3]

array([[13, 13, 18, 18]])

In [142]:
b[0:-2]

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18]])

In [143]:
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [144]:
b[0:2]

array([[11, 19, 10, 16],
       [10, 14, 18, 14]])

In [145]:
b[0,2]

10

In [146]:
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [147]:
b[-5,-3]

19

In [148]:
b[-4,2]

18

In [149]:
np.random.randint(10,20,(4,4))

array([[14, 17, 10, 14],
       [19, 10, 16, 14],
       [12, 14, 16, 13],
       [13, 17, 18, 15]])

In [150]:
b

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

In [151]:
b[-4,-2]

18

In [152]:
b[-4:2]

array([[10, 14, 18, 14]])

In [153]:
b[:]

array([[11, 19, 10, 16],
       [10, 14, 18, 14],
       [13, 13, 18, 18],
       [17, 10, 13, 18],
       [17, 17, 11, 18]])

- Operations

In [154]:
a =np.random.randint(10,20,10)
a

array([10, 18, 15, 14, 17, 14, 11, 13, 13, 19])

In [155]:
id(a)

1818296473360

In [156]:
arr2 =np.random.randint(0,100,(10,10))
arr2

array([[18, 34, 51, 30, 53, 58, 43, 55, 18, 45],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35],
       [58, 49, 73, 44, 13, 70, 38, 39,  8, 13],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [84, 89, 66, 60, 16, 56, 23, 24,  4, 49],
       [87, 30, 54, 25, 20, 97, 57, 23, 27, 29],
       [33, 53, 51, 86,  7,  9, 54,  0, 83, 36],
       [81, 20,  3, 42, 65, 20, 36, 68, 80, 47],
       [10, 94, 91, 43, 63, 31, 20, 70,  9, 60],
       [91, 35, 83, 76, 18, 74, 98, 97, 43,  3]])

In [157]:
arr

array([0, 1, 2, 3, 4, 5])

In [158]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [159]:
arr[0:]

array([0, 1, 2, 3, 4, 5])

In [160]:
arr2[:]

array([[18, 34, 51, 30, 53, 58, 43, 55, 18, 45],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35],
       [58, 49, 73, 44, 13, 70, 38, 39,  8, 13],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [84, 89, 66, 60, 16, 56, 23, 24,  4, 49],
       [87, 30, 54, 25, 20, 97, 57, 23, 27, 29],
       [33, 53, 51, 86,  7,  9, 54,  0, 83, 36],
       [81, 20,  3, 42, 65, 20, 36, 68, 80, 47],
       [10, 94, 91, 43, 63, 31, 20, 70,  9, 60],
       [91, 35, 83, 76, 18, 74, 98, 97, 43,  3]])

In [161]:
arr2[:5]

array([[18, 34, 51, 30, 53, 58, 43, 55, 18, 45],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35],
       [58, 49, 73, 44, 13, 70, 38, 39,  8, 13],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [84, 89, 66, 60, 16, 56, 23, 24,  4, 49]])

In [162]:
arr2[1,4]

48

In [164]:
arr2[-5,5]

97

In [165]:
arr2[-5,-5]

97

In [166]:
arr2[-1,-2]

43

In [167]:
arr2

array([[18, 34, 51, 30, 53, 58, 43, 55, 18, 45],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35],
       [58, 49, 73, 44, 13, 70, 38, 39,  8, 13],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [84, 89, 66, 60, 16, 56, 23, 24,  4, 49],
       [87, 30, 54, 25, 20, 97, 57, 23, 27, 29],
       [33, 53, 51, 86,  7,  9, 54,  0, 83, 36],
       [81, 20,  3, 42, 65, 20, 36, 68, 80, 47],
       [10, 94, 91, 43, 63, 31, 20, 70,  9, 60],
       [91, 35, 83, 76, 18, 74, 98, 97, 43,  3]])

In [168]:
arr2[::-1]

array([[91, 35, 83, 76, 18, 74, 98, 97, 43,  3],
       [10, 94, 91, 43, 63, 31, 20, 70,  9, 60],
       [81, 20,  3, 42, 65, 20, 36, 68, 80, 47],
       [33, 53, 51, 86,  7,  9, 54,  0, 83, 36],
       [87, 30, 54, 25, 20, 97, 57, 23, 27, 29],
       [84, 89, 66, 60, 16, 56, 23, 24,  4, 49],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [58, 49, 73, 44, 13, 70, 38, 39,  8, 13],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35],
       [18, 34, 51, 30, 53, 58, 43, 55, 18, 45]])

In [169]:
arr2[::-2]

array([[91, 35, 83, 76, 18, 74, 98, 97, 43,  3],
       [81, 20,  3, 42, 65, 20, 36, 68, 80, 47],
       [87, 30, 54, 25, 20, 97, 57, 23, 27, 29],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35]])

In [170]:
arr2[::-3]

array([[91, 35, 83, 76, 18, 74, 98, 97, 43,  3],
       [33, 53, 51, 86,  7,  9, 54,  0, 83, 36],
       [ 7, 80, 22, 79, 89,  8, 99,  6, 81, 71],
       [18, 34, 51, 30, 53, 58, 43, 55, 18, 45]])

In [171]:
arr2[::-4]

array([[91, 35, 83, 76, 18, 74, 98, 97, 43,  3],
       [87, 30, 54, 25, 20, 97, 57, 23, 27, 29],
       [87, 65, 70, 53, 48, 94, 59, 80, 26, 35]])

- Max,min,mean,

In [173]:
arr

array([0, 1, 2, 3, 4, 5])

In [174]:
arr.max()

5

In [175]:
arr.min()

0

In [176]:
arr.mean()

2.5

In [177]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [178]:
from numpy import *
a = array([1,2,3,4,5,6,7,8,9])
median(a)

5.0

# Without work on import * can you plese find the Median , Mode

- Reshape Function

In [190]:
arr

array([0, 1, 2, 3, 4, 5])

In [191]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [192]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [193]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [194]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [195]:
arr.reshape(3,2,order='c')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [196]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [197]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [198]:
arr

array([0, 1, 2, 3, 4, 5])

In [199]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [200]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

- Indexing 

In [201]:
mat = np.arange(0,100).reshape(10,10)

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
row = 4
col = 5

In [204]:
row 

4

In [205]:
col

5

In [206]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[row,col]

45

In [208]:
mat[4,5]

45

In [209]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
col = 6

In [211]:
col

6

In [212]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [213]:
mat[col]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [214]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [215]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [216]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [217]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [218]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [219]:
row

4

In [220]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [221]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[1,4]

14

In [225]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [226]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [227]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [229]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [230]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [231]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [232]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [236]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [237]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [238]:
mat[2:7]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [239]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [240]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [241]:
mat[0,1]

1

In [242]:
mat[2:8,6:8]

array([[26, 27],
       [36, 37],
       [46, 47],
       [56, 57],
       [66, 67],
       [76, 77]])

In [243]:
mat[1:4,3:5]

array([[13, 14],
       [23, 24],
       [33, 34]])

In [244]:
mat[2:5,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [245]:
mat[1:2,2:4]

array([[12, 13]])

In [246]:
mat[2:3,2:3]

array([[22]])

In [247]:
mat[5:7,5:7]

array([[55, 56],
       [65, 66]])

In [248]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [249]:
mat[2:3,4:5]

array([[24]])

- Masking

In [250]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [251]:
id(mat)

1818296678992

In [252]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [253]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [254]:
mat[mat ==50]

array([50])

In [255]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [256]:
a1 = mat[mat<50]

In [257]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [258]:
a2 =mat[mat>50]

In [259]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [260]:
a3 =mat[mat<=50]

In [261]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [262]:
a4 =mat[mat==50]
a4

array([50])

# Python program generat OTP

In [263]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 1353


In [264]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [265]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [266]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001A758CE35C0>


In [267]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
